== Setting Up the Development Environment for SC-OBC Module A1

=== Prepare the Software

==== Target Platform

This guide is focused on *Ubuntu 24.04 x86_64* systems.

You can use any of the following setups:

* A PC with Ubuntu installed
* A system container (e.g., Incus)
* A virtual machine (e.g., QEMU, VirtualBox, VMware)
* WSL2 (build only, no flashing)
** Due to issues finding executables, the Zephyr Project doesn’t currently support application flashing using the WSL2.

For Windows or macOS users, refer to link:https://docs.zephyrproject.org/latest/develop/getting_started/index.html[the official Zephyr documentation].

==== Install Required Dependencies

[INFO]
======
This section is mostly the same as Zephyr official documentation.
======

===== Update your system

[source, bash]
----
$ sudo apt update && sudo apt upgrade
----

===== Install dependencies

[source, bash]
----
$ sudo apt install --no-install-recommends git cmake ninja-build gperf \
  ccache dfu-util device-tree-compiler wget \
  python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
  make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
----

==== Get Zephyr and Python Requirements

===== Create your working directory

[source, bash]
----
$ mkdir -p ~/myproject && cd ~/myproject
----

===== Install Python venv package

[source, bash]
----
$ sudo apt install python3-venv
----

===== Create a new virtual environment

[source, bash]
----
$ python3 -m venv ~/myproject/.venv
----

===== Activate the virtual environment

[source, bash]
----
$ source ~/myproject/.venv/bin/activate
----

===== Install West

[source, bash]
----
$ pip install west
----

===== Clone the SC-OBC Module A1 sample repository using West

[source, bash]
----
$ cd ~/myproject
$ west init -m https://github.com/spacecubics/scobc-a1-sample.git
$ west update
$ west zephyr-export
----

===== Install Python requirements

[source, bash]
----
$ pip install -r zephyr/scripts/requirements.txt
----

==== Install Zephyr SDK

[source, bash]
----
$ west sdk install
----

==== Install the udev rules

Install the udev rules, which allow you to flash most Zephyr boards as a regular user.

[source, bash]
----
$ sudo cp ~/zephyr-sdk-[VERSION]/sysroots/x86_64-pokysdk-linux/usr/share/openocd/contrib/60-openocd.rules \
          /etc/udev/rules.d
$ sudo udevadm control --reload
----

