== Try developing applications on SC-OBC Module A1

=== Introduction

This section explains how to develop applications using Zephyr's T2 topology. +
Several sample applications are provided to help explain the source code structure, build process, and other development practices.

=== What's T2 topology

Details of the T2 topology can be found in https://docs.zephyrproject.org/latest/develop/west/workspaces.html#t2-star-topology-application-is-the-manifest-repository[T2 topology], but it has the following characteristics:

 * Applications can be managed in a dedicated (custom) repository
 * Zephyr and other projects can be managed as sub modules
 * Zephyr drivers can be managed out-of-tree in a dedicated (custom) repository

=== Example

==== Hello World

This section provides an example of building and running the simplest _Hello World_ application within a T2 topology-based repository. +
The sample application is available at the following repository:

 * https://github.com/sasataku/scobc-a1-sample/sample/hello_world

===== Explain the sample code

====== Directory name

The directory name and structure for the sample application can be chosen freely. +
In this example, we use the directory name `sample/hello_world`.

====== CMakefile.txt

A `CMakeLists.txt` file must be placed directly under the application directory.

[source, bash]
----
cmake_minimum_required(VERSION 3.20.0)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(hello-world)

target_sources(app PRIVATE src/main.c)
----

Here, the parts that need to be modified for each application are explained.

 * _project_: Specify the desired project name
 * _target_sources_: Specify the source code file(s)

====== prj.conf

Additional _Kconfig_ parameters required for running the application can be specified. +
For this _Hello World_ application, no additional parameters are required, so leaving it empty is fine.

[source, bash]
----
# nothing here
----

====== Source code

The source code is equivalent to the sample code provided by Zephyr, but the displayed parameters have been modified. +
In the Zephyr sample code, `CONFIG_BOARD_TARGET` was displayed, but in this sample, the board name (`CONFIG_BOARD`) and the revision (`CONFIG_BOARD_REVISION`) are displayed separately.
[source, c]
----
/*
 * Copyright (c) 2025 Space Cubics, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <stdio.h>

int main(void)
{
	printf("Hello World! %s Rev %s\n", CONFIG_BOARD, CONFIG_BOARD_REVISION);

	return 0;
}
----

TIP: The variable names starting with `CONFIG_` store parameters specified in Zephyr's _Kconfig_. To know all the _Kconfig_ parameters, you can refer to the `<build_directory>/zephyr/zephyr.dts` file.

==== Build

Specify the sample application directory where `CMakeLists.txt` and `prj.conf` are placed, and then build as shown below.

[source, bash]
----
$ west build -p always -b scobc_a1 --shield scobc_a1_devkit scobc-a1-sample/sample/hello_world
----

==== Flash

Then, as before, execute the flashing by running `west flash`.

[source, bash]
----
$ west flash
----

==== Confirm

The "Hello World" string will be displayed on the serial console along with the board name and revision.

[source, bash]
----
*** Booting Zephyr OS build v4.1.0-4989-g0c876f7c1d5f ***
Hello World! scobc_a1 Rev 2.0.0
----

==== System Monitor

This section provides an example of building and running the _System Monitor_ application within a T2 topology-based repository.

===== What's _System Monitor_

Details of the _System Monitor_ can be found in https://sc-obc-fpga-technical-reference-manual.readthedocs.io/ja/latest/#org8832978[System Monitor], but it has the following characteristics:

FPGA Watchdog::

The system of the SC-OBC Module A1 is monitored by the _TRCH_ (Timing, Reset, Config & Health Controller), and the FPGA reports its internal status to the _TRCH_ via the watchdog signal.

NOTE: the Monitoring by TRCH is disabled by default, so using the _FPGA Watchdog_ feature is not mandatory.

SEM Controller::

The _SEM (Soft Error Mitigation) Controller_ is a solution provided by _AMD_ for detecting and correcting errors that occur in the configuration memory of AMD FPGAs. +
The SC-OBC Module A1 FPGA integrates this functionality into the system and provides access to the _SEM Controller_'s status through the System Monitor registers.

Board Health Monitor (BHM)::

The _Board Health Monitor (BHM)_ is a feature that enables easy retrieval of data from sensors mounted on the SC-OBC Module A1. +
The OBC module is equipped with two current and voltage monitors and three temperature sensors. +
The _BHM_ allows automatic data acquisition from these sensors without requiring complex I2C operations in software.

===== _System Monitor_ driver

Currently, the following Zephyr driver APIs are provided for controlling the FPGA's System Monitor.

[[anchor-1]]
.System Monitor Driver API List
[options="header"]
|=======================
|Function|API|Summary|Parameters|Returns
|FPGA Watchdog|sc_kick_wdt_timer|Toggle the FPGA Watch Dog Timer||
|SEM Controller|sc_sem_get_error_count|Get the SEM error count||Current SEM error count
|Board Health Monitor (BHM)|sc_bhm_enable|Enable the monitoring by BHM +
*NOTE:* Currently monitoring interval is fixed by 1 seconds||*0:* Success +
*-ETIMEDOUT:* Timeout for sensor device initializing
||sc_bhm_disable|Disable the monitoring by BHM||*0:* Success
||sc_bhm_get_obc_temp|Get the on board temperature sensor value|*pos:* Position for sensor device +
<Selectable parameter> +
_SCOBC_A1_TEMP_1_ +
_SCOBC_A1_TEMP_2_ +
_SCOBC_A1_TEMP_3_ +
 +
*temp* Temperature [degree]|*0:* Success +
*-ENODEV:* Wrong parameter +
*--EAGAIN:* No updated sensor values
||sc_bhm_get_xadc_temp|Get the FPGA DAI temperature sensor value|*temp:* Temperature [degree]|*0:* Success +
*--EAGAIN:* No updated sensor values
||sc_bhm_get_obc_cv|Get the on board Current/Voltage sensor value|*pos:* Position for sensor device +
<Selectable parameter> +
_SCOBC_A1_1V0_SHUNT_ +
_SCOBC_A1_1V0_BUS_ +
_SCOBC_A1_1V8_SHUNT_ +
_SCOBC_A1_1V8_BUS_ +
_SCOBC_A1_3V3_SHUNT_ +
_SCOBC_A1_3V3_BUS_ +
_SCOBC_A1_3V3_SYSA_SHUNT_ +
_SCOBC_A1_3V3_SYSA_BUS_ +
_SCOBC_A1_3V3_SYSB_SHUNT_ +
_SCOBC_A1_3V3_SYSB_BUS_ +
_SCOBC_A1_3V3_IO_SHUNT_ +
_SCOBC_A1_3V3_IO_BUS_ +
 +
*cv:* Current sensor value [mA] / Voltage sensor value [mV] |*0:* Success +
*--EAGAIN:* No updated sensor values
||sc_bhm_get_xadc_cv|Get the FPGA voltage value|*pos:* Position for sensor device +
<Selectable parameter> +
_SCOBC_A1_XADC_VCCINT_ +
_SCOBC_A1_XADC_VCCAUX_ +
_SCOBC_A1_XADC_VCCBRAM_ +
 +
*cv:* FPGA Voltage value [mV] |*0:* Success +
*--EAGAIN:* No updated sensor values
|=======================

These APIs are provided as an out-of-tree driver and are available in the following repository.

 * https://github.com/sasataku/scobc-a1-sample/drivers/misc/sc_fpga

===== _System Monitor_ sample application

The sample application is available at the following repository:

 * https://github.com/sasataku/scobc-a1-sample/sample/hello_world

===== Explain the sample code

====== Directory name

The directory name and structure for the sample application can be chosen freely. +
In this example, we use the directory name `sample/sysmon`.

====== CMakefile.txt

A `CMakeLists.txt` file must be placed directly under the application directory.

[source, bash]
----
cmake_minimum_required(VERSION 3.20.0)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(system-monitor)

target_sources(app PRIVATE src/main.c)
----

Here, the parts that need to be modified for each application are explained.

 * _project_: Specify the desired project name
 * _target_sources_: Specify the source code file(s)

====== prj.conf

Additional _Kconfig_ parameters required for running the application can be specified. +
For this _Hello World_ application, no additional parameters are required, so leaving it empty is fine.

[source, bash]
----
# nothing here
----

====== Source code

The source code is shown below. Details will be explained separately.

[source, c]
----
/*
 * Copyright (c) 2025 Space Cubics, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/kernel.h>
#include "sc_sysmon.h"

int main(void)
{
	int ret;
	float temp;
	int32_t bus;
	float vcc;

	ret = sc_bhm_enable();
	if (ret < 0) {
		printf("Failed to enable the Board Health Monitor: %d\n", ret);
		goto end;
	}

	/* Wait for the first monitoring to finish */
	k_sleep(K_SECONDS(1));

	while (true) {
		ret = sc_bhm_get_obc_temp(SCOBC_A1_TEMP_1, &temp);
		if (ret < 0) {
			printf("Failed to get the on Board temperature 1: %d\n", ret);
			goto end;
		}
		printf("On Board tempareture 1 : %.4f [deg]\n", (double)temp);

		ret = sc_bhm_get_obc_cv(SCOBC_A1_3V3_BUS, &bus);
		if (ret < 0) {
			printf("Failed to get the 3V3SYS Bus voltage: %d\n", ret);
			goto end;
		}
		printf("3V3SYS Bus voltage     : %d [mv]\n", bus);

		k_sleep(K_SECONDS(1));
	}

end:
	sc_bhm_disable();

	return ret;
}
----

* Include _System Monitor_ driver header

Include the header file for the _System Monitor_ driver.

[source, c]
----
#include "sc_sysmon.h"
----

* Enable BHM

Enable the _System Monitor_ by FPGA _BHM_. If a non-zero value is returned, sensor initialization has failed.

[source, c]
----
	ret = sc_bhm_enable();
	if (ret < 0) {
		printf("Failed to enable the Board Health Monitor: %d\n", ret);
		goto end;
	}
----

* Wait 1 seconds

The current _System Monitor_ driver API does not allow customization of the monitoring interval via BHM; + 
it is fixed at 1 second. Therefore, waits for 1 second until the first data collection is completed.

[source, c]
----
	k_sleep(K_SECONDS(1));
----

* Get the on board temperature sensor value

Get the temperature data from onboard temperature sensor 1 and display it on the console. +
If a non-zero value is returned, it may indicate that the temperature sensor data has not been updated within the FPGA. +
If you'd like to get other values, try changing the _SCOBC_A1_TEMP_1_ to a different parameter of your choice, as referenced in <<anchor-1,Table 1. System Monitor Driver API List>>

[source, c]
----
		ret = sc_bhm_get_obc_temp(SCOBC_A1_TEMP_1, &temp);
		if (ret < 0) {
			printf("Failed to get the on Board temperature 1: %d\n", ret);
			goto end;
		}
		printf("On Board tempareture 1 : %.4f [deg]\n", (double)temp);
----

* Get the on board voltage sensor value

Get the _3V3SYS_ BUS voltage value data from onboard voltage sensor and display it on the console. +
If a non-zero value is returned, it may indicate that the temperature sensor data has not been updated within the FPGA. +
If you'd like to get other values, try changing the _SCOBC_A1_3V3_BUS_ to a different parameter of your choice, as referenced in <<anchor-1,Table 1. System Monitor Driver API List>>

[source, c]
----
		ret = sc_bhm_get_obc_cv(SCOBC_A1_3V3_BUS, &bus);
		if (ret < 0) {
			printf("Failed to get the 3V3SYS Bus voltage: %d\n", ret);
			goto end;
		}
		printf("3V3SYS Bus voltage     : %d [mv]\n", bus);
----

==== Build

Specify the sample application directory where `CMakeLists.txt` and `prj.conf` are placed, and then build as shown below.

[source, bash]
----
$ west build -p always -b scobc_a1 --shield scobc_a1_devkit scobc-a1-sample/sample/sysmon
----

==== Flash

Then, as before, execute the flashing by running `west flash`.

[source, bash]
----
$ west flash
----

==== Confirm

Confirm that the temperature from the on board temperature sensor and the _3V3SYS_ bus voltage are displayed on the console every second.

[source, bash]
----
*** Booting Zephyr OS build v4.1.0-4990-g8ce593be113f ***
On Board Tempareture 1 : 28.5000 [deg]
3V3SYS Bus voltage     : 3256 [mv]
On Board Tempareture 1 : 28.5000 [deg]
3V3SYS Bus voltage     : 3256 [mv]
On Board Tempareture 1 : 28.5000 [deg]
3V3SYS Bus voltage     : 3256 [mv]
----
