== Try applications development using Zephyr Driver

=== Introduction

This section explains how to develop applications using Zephyr Driver. +
Several sample applications are provided to explain how to check the _Devicetree_ and how to use drivers.

=== Example

==== GPIO Driver

Using this GPIO driver, the LED on the _Development Board_ will blink.
The sample application is available at the following location.

 * https://github.com/spacecubics/scobc-a1-sample/sample/blinky/

===== Explain the sample code

====== Directory Name

The directory name and structure for the sample application can be chosen freely. +
In this example, we use the directory name `sample/blinky`.

====== CMakefile.txt

A `CMakeLists.txt` file must be placed directly under the application directory.

[source, bash]
----
cmake_minimum_required(VERSION 3.20.0)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(blinky)

target_sources(app PRIVATE src/main.c)
----

Here, the parts that need to be modified for each application are explained.

 * _project_: Specify the desired project name
 * _target_sources_: Specify the source code file(s)

====== prj.conf

Additional _Kconfig_ parameters required for running the application can be specified. +
As this example uses GPIO, it is necessary to set `CONFIG_GPIO=y`.

[source, bash]
----
CONFIG_GPIO=y
----

====== Source code

The source code is shown below. Details will be explained separately.

[source, c]
----
/*
 * Copyright (c) 2025 Space Cubics, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/drivers/gpio.h>

int main(void)
{
	int ret;
	const struct gpio_dt_spec led = GPIO_DT_SPEC_GET(DT_ALIAS(led0), gpios);
	bool led_state = true;

	if (!gpio_is_ready_dt(&led)) {
		printf("GPIO device is not ready\n");
		return -1;
	}

	ret = gpio_pin_configure_dt(&led, GPIO_OUTPUT_ACTIVE);
	if (ret < 0) {
		printf("Failed to configure a GPIO pin (%d)\n", ret);
		return -1;
	}

	while (true) {
		ret = gpio_pin_toggle_dt(&led);
		if (ret < 0) {
			printf("Failed to toggle a GPIO pin (%d)\n", ret);
			return -1;
		}

		led_state = !led_state;
		printf("LED state: %s\n", led_state ? "ON" : "OFF");
		k_sleep(K_SECONDS(1));
	}

	return 0;
}
----

* GPIO Device structure

The SC OBC Module A1 is equipped with AMD (formerly Xilinx)'s AXI GPIO IP core, which connects to 8 GPIOs. +
The relationship between the GPIOs and the User IO pins is as follows, with `GPIO7` connected to the LED on the _Development Board_.

.GPIO pins List
[options="header"]
|=======================
|User IO pin name|GPIO name in AMD GPIO IP core
|UIO2_15|GPIO7
|UIO2_14|GPIO6
|UIO2_13|GPIO5
|UIO2_12|GPIO4
|UIO2_11|GPIO3
|UIO2_10|GPIO2
|UIO2_09|GPIO1
|UIO2_08|GPIO0
|=======================

Referring to the following DTS file, it can be seen that `GPIO7` of the GPIO IP core is defined with the device name `led0`. +
Additionally, an `led0` is assigned using the alias, which is used by Zephyr's blinky sample. However, this alias is not mandatory.

[source, c]
----
	aliases {
		led0 = &led0;
	};

	leds {
		compatible = "gpio-leds";
		led0: led0 {
			gpios = <&gpio0 7 GPIO_ACTIVE_HIGH>;
		};
	};
----

Therefore, in this example, the GPIO device structure is obtained using `GPIO_DT_SPEC_GET` and `DT_ALIAS`.

[source, c]
----
	const struct gpio_dt_spec led = GPIO_DT_SPEC_GET(DT_ALIAS(led0), gpios);
----

* Validate that GPIO port is ready

Validate that GPIO port is ready. If the GPIO device is not properly initialized, it will return `false`.

[source, c]
----
	if (!gpio_is_ready_dt(&led)) {
		printf("GPIO device is not ready\n");
		return -1;
	}
----

* Configure a GPIO pin

The GPIO is configured to its initial state as `OUTPUT_ACTIVE`. If the configuration fails, a non-zero value will be returned.

[source, c]
----
	ret = gpio_pin_configure_dt(&led, GPIO_OUTPUT_ACTIVE);
	if (ret < 0) {
		printf("Failed to configure a GPIO pin (%d)\n", ret);
		return -1;
	}
----

* Toggle a GPIO pin

Toggle the GPIO pin. If the toggle fails, a non-zero value will be returned.

[source, c]
----
	ret = gpio_pin_toggle_dt(&led);
	if (ret < 0) {
		printf("Failed to toggle a GPIO pin (%d)\n", ret);
		return -1;
	}
----

==== Build

Specify the sample application directory where `CMakeLists.txt` and `prj.conf` are placed, and then build as shown below.

[source, bash]
----
$ west build -p always -b scobc_a1 --shield scobc_a1_devkit scobc-a1-sample/sample/i2c
----

==== Flash

Then, as before, execute the flashing by running `west flash`.

[source, bash]
----
$ west flash
----

==== Confirm

The LED will blink on and off every second, and the LED state will be displayed on the console.

[source, bash]
----
*** Booting Zephyr OS build v4.1.0-4622-g4c5375ecd654 ***
LED state: OFF
LED state: ON
LED state: OFF
LED state: ON
----

==== I2C Driver

Using the I2C driver for the SC-OBC Module A1, this application gets a temperature data from the sensor on the _Development Board_ and displays it on the console.
The sample application is available at the following location.

 * https://github.com/spacecubics/scobc-a1-sample/sample/i2c/

===== Explain the sample code

====== Directory Name

The directory name and structure for the sample application can be chosen freely. +
In this example, we use the directory name `sample/i2c`.

====== CMakefile.txt

A `CMakeLists.txt` file must be placed directly under the application directory.

[source, bash]
----
cmake_minimum_required(VERSION 3.20.0)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(i2c-sample)

target_sources(app PRIVATE src/main.c)
----

Here, the parts that need to be modified for each application are explained.

 * _project_: Specify the desired project name
 * _target_sources_: Specify the source code file(s)

====== prj.conf

Additional _Kconfig_ parameters required for running the application can be specified. +
As this example uses I2C, it is necessary to set `CONFIG_I2C=y`.

[source, bash]
----
CONFIG_I2C=y
----

====== Source code

The source code is shown below. Details will be explained separately.

[source, c]
----
/*
 * Copyright (c) 2025 Space Cubics, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/drivers/i2c.h>

#define TMP175_I2C_ADDR (0x4B)
#define TMP175_TEMP_REG (0x00)

int main(void)
{
	int ret;
	uint8_t data[2];
	float temp;

	const struct device *i2c = DEVICE_DT_GET(DT_NODELABEL(i2c0));

	ret = i2c_burst_read(i2c, TMP175_I2C_ADDR, TMP175_TEMP_REG, data, ARRAY_SIZE(data));
	if (ret < 0) {
		printf("Failed to read from Temperature Sensor (%d)\n", ret);
		goto end;
	}

	data[1] = data[1] >> 4;
	temp = (int8_t)data[0] + (float)data[1] * 0.0625f;

	printf("Temperature: %.4f [deg]\n", (double)temp);

end:
	return ret;
}
----

* Device structure

To use the I2C driver API, it is necessary to obtain the corresponding device structure. +
There are several APIs available for retrieving a device structure, but in this sample, `DEVICE_DT_GET` and `DT_NODELABEL` are used. +
The label name specified in `DT_NODELABEL` must match the label defined in the DTS file.
The I2C device connected to the temperature sensor on the development board is defined in the following DTS file.

 ** https://github.com/spacecubics/scobc-a1-sample/blob/main/boards/shields/scobc_a1_devkit/scobc_a1_devkit.overlay

Although two FPGA I2C cores are available on the `Development Board`, the temperature sensor is connected to `i2c0`.

[source, c]
----
	const struct device *i2c = DEVICE_DT_GET(DT_NODELABEL(i2c0));
----

TIP: Because the DTS file may be defined across multiple sources via overlays, you may want to inspect the final merged DTS. +
This merged DTS is available in the following file under the build directory. +
 +
`<build_directory>/zephyr/zephyr.dts`

* Validate that I2C device is ready

Validate that I2C device is ready. If the I2C device is not properly initialized, it will return `false`.

[source, c]
----
	if (!device_is_ready(i2c)) {
		printf("I2C device is not ready\n");
		ret = -1;
		goto end;
	}
----

* I2C driver API

The APIs provided by the I2C driver are documented in the I2C interface. +
In this example, it is necessary to read 2 bytes of temperature data from the sensor, so the `i2c_burst_read` API is used to perform a multi-byte read from the I2C device. +
The second argument specifies the slave address of the I2C device. For the _TMP175_ temperature sensor used in this example, the slave address is set to `0x4B`. +
The third argument specifies the register address from which the temperature data will be read.
This register address must be obtained from the _TMP175_ datasheet.
For _TMP175_, the temperature register address is `0x00`.

[source, c]
----
	ret = i2c_burst_read(i2c, TMP175_I2C_ADDR, TMP175_TEMP_REG, data, ARRAY_SIZE(data));
----

* Calucurate tempature data

The _TMP175_ temperature data is represented in 12 bits, and its resolution is `0.0625`. Therefore, the raw value is converted before being printed to the console. +
For more details, please refer to the _TMP175_ datasheet.

[source, c]
----
	data[1] = data[1] >> 4;
	temp = (int8_t)data[0] + (float)data[1] * 0.0625f;
----

==== Build

Specify the sample application directory where `CMakeLists.txt` and `prj.conf` are placed, and then build as shown below.

[source, bash]
----
$ west build -p always -b scobc_a1 --shield scobc_a1_devkit scobc-a1-sample/sample/i2c
----

==== Flash

Then, as before, execute the flashing by running `west flash`.

[source, bash]
----
$ west flash
----

==== Confirm

The temperature data retrieved from the sensor is displayed on the serial console.

[source, bash]
----
*** Booting Zephyr OS build v4.1.0-4622-g4c5375ecd654 ***
Temperature: 31.5000 [deg]
----
