== Setting Up the Development Environment for SC-OBC

=== Prepare the Software

==== Target Platform
This guide is focused on Ubuntu 24.04 x86_64 systems.  You can use
any of the following setups:

* A PC with Ubuntu installed
* A system container (e.g., Incus)
* A virtual machine (e.g., QEMU, VirtualBox, VMware)
* WSL2 (build only, no flashing)
** Due to issues finding executables, the Zephyr Project doesn’t
currently support application flashing using the WSL2.

For Windows or macOS users, refer to the official Zephyr
documentation:
https://docs.zephyrproject.org/latest/develop/getting_started/index.html[https://docs.zephyrproject.org/latest/develop/getting_started/index.html]

==== Install Required Dependencies
💡This section is mostly the same as Zephyr official documentation.

===== Update your system

[source,console]
----
sudo apt update && sudo apt upgrade
----

===== Install dependencies

[source,console]
----
sudo apt install --no-install-recommends git cmake ninja-build gperf \
  ccache dfu-util device-tree-compiler wget \
  python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
  make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
----

==== Get Zephyr and Python Requirements
Create your working directory

[source,console]
----
mkdir -p ~/myproject && cd ~/myproject
----

Use apt to install Python venv package

[source,console]
----
sudo apt install python3-venv
----

Create a new virtual environment

[source,console]
----
python3 -m venv ~/myproject/.venv
----

Activate the virtual environment

[source,console]
----
source ~/myproject/.venv/bin/activate
----

Clone the Zephyr repository using West

[source,console]
----
pip3 install west
west init -m https://github.com/zephyrproject-rtos/zephyr --mr v3.7.0 zephyrproject
west update
west zephyr-export
----

[source,console]
----
git clone https://github.com/spacecubics/scobc-a1-sample
cd scobc-a1-sample
west update
----


Install Python requirements

[source,console]
----
pip3 install -r zephyr/scripts/requirements.txt
----

==== Download & Install Zephyr SDK
Use West sdk install instead,

[source,console]
----
west sdk install
----

Install udev rules, which allow you to flash most Zephyr boards as a regular user

[source,console]
----
sudo cp ~/zephyr-sdk-0.16.8/sysroots/x86_64-pokysdk-linux/usr/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d
sudo udevadm control --reload
----

=== Connect the Hardware
Before starting development, make sure you have the following components:

* ✔️ Module A1
* ✔️ Development Kit
* ✔️ USB Cable
** ✔️ OpenOCD Cable (JTAG/SWD)
** ✔️ USB Serial Interface (UART)
* ✔️ Power Supply
* ✔️ CAN Bus

Add instructions to assert power.

💡 TODO: Add photos or diagrams of each component and instructions on how to connect them.

== Try Sample Applications on SC-OBC module A1
Zephyr RTOS provides many so-called "sample applications". The
Zephyr documentation has a dedicated page called "Samples and
Demos". In this section, we'll build a few samples from Zephyr RTOS
and run them on your module A1.

On the "Samples and Demos" page, you can interactively search
samples. There are over 500 samples in Zephyr v4.1. Using the web
interface is much easier than checking each sample's README.rst.

If you haven't created your workspace yet, go back to the previous
section and do so. In this section, we assume you have already set
up your development environment and are ready to proceed.

=== Blinky
The first sample is Blinky. This application blinks an LED on your
module A1.

[source,console]
----
cd ~/workspace
python3 -m venv ~/zephyrproject/.venv
west build -p always -b scobc-module-a1 samples/basic/blinky
----

This should build your first application, Blinky.

These steps match the "Build the Blinky Sample" section in the
Zephyr documentation.

Next, we'll write the module A1:

[source,console]
----
west flash
----

After flashing, power-cycle the module A1. You should see the
blinking LED (LED1, RED, or whichever LED is configured).

=== Hello World
Next is the ever-popular "Hello World" sample. Before running Hello
World, we need to set up the serial connection so the module can
send output to your PC.

We'll use a USB-to-serial cable.

Connect the cable between your module A1 and your PC, then build the sample:

[source,console]
----
cd ~/workspace
python3 -m venv ~/zephyrproject/.venv
west build -p always -b scobc-module-a1 samples/hello_world
----

After rebooting the module, you should see the "Hello World" string
on your serial console.

=== Dining Philosophers
(Instructions for Dining Philosophers go here.)
