name: vale

on:
  pull_request:
  push:
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Asciidoctor
        run: sudo apt-get update && sudo apt-get install -y asciidoctor

      - name: Run vale
        uses: vale-cli/vale-action@v2
        with:
          version: 3.14.1
          fail_on_error: true
          reporter: github-pr-check
          vale_flags: "--glob=*.adoc --minAlertLevel=error"
          files: "en"
